---
statistical_tests:
  significance_level: 0.05
  replications: 30
  confidence_level: 0.95
algorithms:
- name: "HippopotamusOptimization"
  parameters:
    max_iterations:
    - 100
    - 200
    - 500
    population_size:
    - 20
    - 50
    - 100
    convergence_threshold:
    - 0.001
scalability_tests:
  vm_counts:
  - 100
  - 500
  - 1000
  - 2000
  - 5000
  host_counts:
  - 10
  - 50
  - 100
  - 200
  - 500
datasets:
- "google_traces"
- "azure_traces"
- "synthetic_workloads"
metrics:
- "resource_utilization"
- "power_consumption"
- "sla_violations"
- "response_time"
- "throughput"
